# Generated by Django 2.1.2 on 2018-11-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=128)),
                ('hashed_pass', models.CharField(max_length=128)),
            ],
        ),
    ]
