# Generated by Django 2.1.2 on 2018-12-11 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniordesign', '0002_auto_20181126_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time)),
                ('tags', models.CharField(max_length=50)),
                ('Eventname', models.CharField(max_length=30)),
                ('Host', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('distanceFromUser', models.CharField(max_length=30)),
                ('attandees', models.ManyToManyField(to='seniordesign.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='myEvents',
            field=models.ManyToManyField(to='seniordesign.EventProfile'),
        ),
    ]
