# Generated by Django 2.1.2 on 2018-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniordesign', '0005_remove_uconnectuser_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uconnectuser',
            old_name='photo',
            new_name='profilePic',
        ),
        migrations.RemoveField(
            model_name='uconnectuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='uconnectuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='uconnectuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='uconnectuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='uconnectuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='uconnectuser',
            name='myEvents',
            field=models.ManyToManyField(to='seniordesign.EventProfile'),
        ),
        migrations.AddField(
            model_name='uconnectuser',
            name='university',
            field=models.CharField(default='NYU', max_length=30),
        ),
        migrations.AddField(
            model_name='uconnectuser',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='uconnectuser',
            name='year_in_school',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=15),
        ),
    ]
